email.username=gertocelol@yandex.ru
# ??? ????? ?????? ??????????, ??????? ?????? ??? ?????? ? ???????
email.password=dnrjvwwlqhdatqce
email.from=gertocelol@yandex.com

# ????????? ??????? ???????
mail.smtp.host=smtp.yandex.ru
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.ssl.enable=true
mail.smtp.socketFactory.port=465
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory